<a href="https://www.kaggle.com/code/kattupallisudhakar/ksd-eda-course?scriptVersionId=251071019" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

1.  **Array Creation:**

      * Create a 1D NumPy array `arr1` containing the integers from 0 to 9.
      * Create a 2D NumPy array `arr2` (3x3) filled with all `True` values.
      * Create a 2D NumPy array `arr3` (2x4) with all elements set to 5.

In [1]:
import numpy as np
arr1 = np.arange(10)
print("arr1:", arr1)
arr2 = np.full((3, 3), True, dtype=bool)
print("arr2:\n", arr2)
arr3 = np.full((2, 4), 5)
print("arr3:\n", arr3)

arr1: [0 1 2 3 4 5 6 7 8 9]
arr2:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
arr3:
 [[5 5 5 5]
 [5 5 5 5]]


**Array Properties:**

Given arr1 = np.array([1, 2, 3, 4, 5]), print its data type, shape, and number of dimensions.

In [2]:
arr1_prop = np.array([1, 2, 3, 4, 5])
print("Data type of arr1_prop:", arr1_prop.dtype)
print("Shape of arr1_prop:", arr1_prop.shape)
print("Number of dimensions of arr1_prop:", arr1_prop.ndim)

Data type of arr1_prop: int64
Shape of arr1_prop: (5,)
Number of dimensions of arr1_prop: 1


Indexing and Slicing:

Given arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90]), extract elements from index 2 to 6 (inclusive of 2, exclusive of 6).
Given arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), extract the element at row 1, column 2.
From the same arr, extract the first column.

In [3]:
arr_slice = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
extracted_slice = arr_slice[2:6]
print("Extracted slice:", extracted_slice)

Extracted slice: [30 40 50 60]


Basic Operations:

Create two arrays, a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]). Perform element-wise addition, subtraction, multiplication, and division.
Calculate the sum of all elements in a.
Find the maximum value in b.

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("Sum of a:", np.sum(a))
print("Max of b:", np.max(b))

a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
Sum of a: 6
Max of b: 6


**Boolean Indexing:**

Given arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), extract all odd numbers.
Replace all even numbers in arr with -1.

In [5]:
arr_bool = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr_bool[arr_bool % 2 != 0]
print("Odd numbers:", odd_numbers)
arr_bool[arr_bool % 2 == 0] = -1
print("Array with even numbers replaced:", arr_bool)

Odd numbers: [1 3 5 7 9]
Array with even numbers replaced: [-1  1 -1  3 -1  5 -1  7 -1  9]


Reshaping:

Given arr = np.arange(12), reshape it into a 4x3 2D array.
Reshape the 4x3 array back into a 1D array.

In [6]:
arr_reshape = np.arange(12)
reshaped_arr = arr_reshape.reshape(4, 3)
print("Reshaped (4x3):\n", reshaped_arr)
flattened_arr = reshaped_arr.reshape(-1) # or .flatten()
print("Flattened:", flattened_arr)

Reshaped (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Concatenation and Splitting:

Create arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]). Concatenate them horizontally.
Create arr3 = np.array([[1, 2], [3, 4]]) and arr4 = np.array([[5, 6], [7, 8]]). Concatenate them vertically.
Given arr = np.arange(9).reshape(3, 3), split it into three equal-sized sub-arrays horizontally.

In [7]:
arr1_cat = np.array([1, 2, 3])
arr2_cat = np.array([4, 5, 6])
horizontal_concat = np.hstack((arr1_cat, arr2_cat))
print("Horizontal concatenation:", horizontal_concat)

Horizontal concatenation: [1 2 3 4 5 6]


Broadcasting:

Given arr = np.array([[1, 2, 3], [4, 5, 6]]), add 10 to every element without using a loop.
Given arr = np.array([[1, 2, 3], [4, 5, 6]]) and col = np.array([10, 20]), add col to each row of arr (think about reshaping col if necessary).

In [8]:
arr_broad = np.array([[1, 2, 3], [4, 5, 6]])
added_ten = arr_broad + 10
print("Array + 10:\n", added_ten)

Array + 10:
 [[11 12 13]
 [14 15 16]]


Statistical Operations:

Given arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the mean of each column.
Calculate the standard deviation of the entire array.
Find the minimum value along axis 0 (columns).

In [9]:
arr_stats = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_means = np.mean(arr_stats, axis=0)
print("Mean of each column:", column_means)
std_dev = np.std(arr_stats)
print("Standard deviation of entire array:", std_dev)
min_along_axis0 = np.min(arr_stats, axis=0)
print("Minimum along axis 0 (columns):", min_along_axis0)

Mean of each column: [4. 5. 6.]
Standard deviation of entire array: 2.581988897471611
Minimum along axis 0 (columns): [1 2 3]


Unique Elements and Counts:

Given arr = np.array([1, 2, 1, 3, 2, 4, 5, 4, 1]), find the unique elements.
Count the occurrences of each unique element.

In [10]:
arr_unique = np.array([1, 2, 1, 3, 2, 4, 5, 4, 1])
unique_elements = np.unique(arr_unique)
print("Unique elements:", unique_elements)
unique_elements, counts = np.unique(arr_unique, return_counts=True)
print("Unique elements and their counts:", dict(zip(unique_elements, counts)))

Unique elements: [1 2 3 4 5]
Unique elements and their counts: {1: 3, 2: 2, 3: 1, 4: 2, 5: 1}


Conditional Operations (where):

Given arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), replace all numbers greater than 5 with 100, and all other numbers with 0.

In [11]:
arr_cond = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
result_cond = np.where(arr_cond > 5, 100, 0)
print("Conditional replacement:", result_cond)

Conditional replacement: [  0   0   0   0   0   0 100 100 100 100]


Saving and Loading:

Create an array data = np.arange(100).reshape(10, 10). Save this array to a file named 'my_array.npy'.
Load the 'my_array.npy' file back into a new variable loaded_data. Verify they are identical.

In [12]:
data_save = np.arange(100).reshape(10, 10)
file_name = 'my_array.npy'
np.save(file_name, data_save)
print(f"Array saved to {file_name}")

loaded_data = np.load(file_name)
print("Array loaded from file.")
print("Are original and loaded arrays identical?", np.array_equal(data_save, loaded_data))

Array saved to my_array.npy
Array loaded from file.
Are original and loaded arrays identical? True
